// page.h — HTML page for Relay Show
// Stored as a plain string to avoid raw literal compiler issues.
// This file is included by relay_show.ino

#pragma once

const char PAGE_HTML[] PROGMEM =
"<!doctype html>"
"<html lang='en'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Infinity Sign Systems</title>"
"<style>"
"*{box-sizing:border-box}"
"body{font-family:system-ui,sans-serif;margin:0;padding:16px;background:#0d1b2a;color:#eee;max-width:500px}"
".header{margin-bottom:20px}"
".header h1{margin:0 0 2px;font-size:1.3rem;color:#4fc3f7;letter-spacing:.04em;font-weight:700}"
".header p{margin:0;font-size:.75rem;color:#546e7a}"
".header a{color:#4fc3f7;text-decoration:none}"
".card{background:#132338;border:1px solid #1e3a5f;border-radius:14px;padding:16px;margin-bottom:12px}"
".lbl{font-size:11px;color:#78909c;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;font-weight:600}"
".modes{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}"
".mbtn{padding:14px 6px;border:none;border-radius:10px;font-size:.85rem;font-weight:700;cursor:pointer;background:#1e3a5f;color:#78909c;transition:.15s}"
".mbtn:hover{filter:brightness(1.3)}"
".mbtn:active{filter:brightness(.8)}"
".mbtn.active{color:#fff}"
"#btn-chase.active{background:#0277bd}"
"#btn-pulse.active{background:#6a1b9a}"
"#btn-twinkle.active{background:#e65100}"
".stop-btn{width:100%;margin-top:8px;padding:12px;border:none;border-radius:10px;background:#263238;color:#78909c;font-size:.9rem;font-weight:700;cursor:pointer}"
".stop-btn:hover{background:#37474f;color:#eee}"
".row{display:flex;align-items:center;gap:10px;margin-bottom:12px}"
".row:last-child{margin-bottom:0}"
".row label{font-size:.82rem;color:#90a4ae;min-width:120px}"
"input[type=range]{flex:1;accent-color:#4fc3f7}"
".val{min-width:24px;text-align:right;font-weight:700;color:#4fc3f7;font-size:.85rem}"
".ctrl-chase,.ctrl-pulse,.ctrl-twinkle{display:none}"
".grid{display:grid;grid-template-columns:repeat(8,1fr);gap:5px}"
".led{height:26px;border-radius:6px;background:#1e3a5f;transition:.1s}"
".led.on{background:#e94560;box-shadow:0 0 8px #e9456055}"
".bsep{font-size:.68rem;color:#37474f;text-align:center;margin:6px 0 4px;letter-spacing:.05em}"
".status{font-size:.72rem;color:#37474f;text-align:center;margin-top:6px}"
"</style>"
"</head>"
"<body>"
"<div class='header'>"
"<h1>Infinity Sign Systems</h1>"
"<p><a href='http://infinitysignsystems.com' target='_blank'>infinitysignsystems.com</a> &nbsp;|&nbsp; 816.252.3337</p>"
"</div>"
"<div class='card'>"
"<div class='lbl'>Animation</div>"
"<div class='modes'>"
"<button class='mbtn' id='btn-chase'   onclick='setMode(\"chase\")'>&#9646; Chase</button>"
"<button class='mbtn' id='btn-pulse'   onclick='setMode(\"pulse\")'>&#9672; Pulse</button>"
"<button class='mbtn' id='btn-twinkle' onclick='setMode(\"twinkle\")'>&#10022; Twinkle</button>"
"</div>"
"<button class='stop-btn' onclick='setMode(\"stopped\")'>&#9632; Stop</button>"
"</div>"
"<div class='card'>"
"<div class='lbl'>Settings</div>"
"<div class='row'>"
"<label>Speed</label>"
"<input type='range' id='speed' min='1' max='10' step='1' value='5' oninput='document.getElementById(\"speedVal\").textContent=this.value;sendSettings()'>"
"<span class='val' id='speedVal'>5</span>"
"</div>"
"<div class='row ctrl-chase'>"
"<label>Notch Width</label>"
"<input type='range' id='notchWidth' min='1' max='8' step='1' value='2' oninput='document.getElementById(\"widthVal\").textContent=this.value;sendSettings()'>"
"<span class='val' id='widthVal'>2</span>"
"</div>"
"<div class='row ctrl-chase'>"
"<label>Notch Count</label>"
"<input type='range' id='notchCount' min='1' max='8' step='1' value='3' oninput='document.getElementById(\"countVal\").textContent=this.value;sendSettings()'>"
"<span class='val' id='countVal'>3</span>"
"</div>"
"<div class='row ctrl-pulse'>"
"<label>Pulse Width</label>"
"<input type='range' id='pulseWidth' min='1' max='12' step='1' value='3' oninput='document.getElementById(\"pulseWidthVal\").textContent=this.value;sendSettings()'>"
"<span class='val' id='pulseWidthVal'>3</span>"
"</div>"
"<div class='row ctrl-twinkle'>"
"<label>Sparkle Size</label>"
"<input type='range' id='sparkleSize' min='1' max='4' step='1' value='2' oninput='document.getElementById(\"sparkleVal\").textContent=this.value;sendSettings()'>"
"<span class='val' id='sparkleVal'>2</span>"
"</div>"
"</div>"
"<div class='card'>"
"<div class='lbl'>Live State</div>"
"<div class='bsep'>Board 1 &mdash; Ch 1&ndash;8</div>"
"<div class='grid' id='gA'></div>"
"<div class='bsep'>Board 2 &mdash; Ch 9&ndash;16</div>"
"<div class='grid' id='gB'></div>"
"<div class='bsep'>Board 3 &mdash; Ch 17&ndash;24</div>"
"<div class='grid' id='gC'></div>"
"</div>"
"<div class='status' id='status'>Connecting...</div>"
"<script>"
"['A','B','C'].forEach(function(g,bi){"
"var el=document.getElementById('g'+g);"
"for(var i=0;i<8;i++){"
"var d=document.createElement('div');"
"d.className='led';"
"d.id='led'+(bi*8+i);"
"el.appendChild(d);"
"}"
"});"
"function setMode(m){"
"fetch('/mode?m='+m,{method:'POST'})"
".then(function(r){return r.json();})"
".then(updateUI)"
".catch(function(){});"
"}"
"function sendSettings(){"
"var p='speed='+document.getElementById('speed').value"
"+'&notchWidth='+document.getElementById('notchWidth').value"
"+'&notchCount='+document.getElementById('notchCount').value"
"+'&pulseWidth='+document.getElementById('pulseWidth').value"
"+'&sparkleSize='+document.getElementById('sparkleSize').value;"
"fetch('/settings?'+p,{method:'POST'}).catch(function(){});"
"}"
"function updateUI(d){"
"['chase','pulse','twinkle'].forEach(function(m){"
"var btn=document.getElementById('btn-'+m);"
"if(btn) btn.className='mbtn'+(d.mode===m?' active':'');"
"});"
"var sc=d.mode==='chase'?'flex':'none';"
"var sp=d.mode==='pulse'?'flex':'none';"
"var st=d.mode==='twinkle'?'flex':'none';"
"document.querySelectorAll('.ctrl-chase').forEach(function(e){e.style.display=sc;});"
"document.querySelectorAll('.ctrl-pulse').forEach(function(e){e.style.display=sp;});"
"document.querySelectorAll('.ctrl-twinkle').forEach(function(e){e.style.display=st;});"
"if(document.activeElement.type!=='range'){"
"document.getElementById('speed').value=d.speed;"
"document.getElementById('notchWidth').value=d.notchWidth;"
"document.getElementById('notchCount').value=d.notchCount;"
"document.getElementById('pulseWidth').value=d.pulseWidth;"
"document.getElementById('sparkleSize').value=d.sparkleSize;"
"document.getElementById('speedVal').textContent=d.speed;"
"document.getElementById('widthVal').textContent=d.notchWidth;"
"document.getElementById('countVal').textContent=d.notchCount;"
"document.getElementById('pulseWidthVal').textContent=d.pulseWidth;"
"document.getElementById('sparkleVal').textContent=d.sparkleSize;"
"}"
"for(var i=0;i<24;i++){"
"var led=document.getElementById('led'+i);"
"if(led) led.className='led'+(d.relays[i]?' on':'');"
"}"
"var sb=document.getElementById('status');"
"sb.textContent=d.mode==='stopped'?'Stopped - settings saved':'Running: '+d.mode+' - '+new Date().toLocaleTimeString();"
"}"
"setInterval(function(){"
"fetch('/state').then(function(r){return r.json();}).then(updateUI).catch(function(){});"
"},200);"
"</script>"
"</body>"
"</html>";